guard :java,  :project_name   => 'My Java Project',
              :all_after_pass => false,                   # run the all_cli command if the specific test class passes (true/false)
              :focused_cli    => 'ant clean debug',       # (required) command-line to run before running a specific test class
              :all_cli        => 'ant package-and-test',  # (required) command-line to run that executes the "build and run all tests" concept
              :classpath      => './bin/classes.jar:./libs/*:/usr/share/java/junit.jar' # (required) don't forget junit and your own jars here
            # :all_on_start   => true                     # run all on startup of guard
            # junit_runner_class => 'org.junit.runner.JUnitCore' # just in case you're using JUnit 3 or something other than 4
  do

  watch (%r{^tests/src/*/(.+)\.java$})  # Test file changes
  watch(%r{^src/*/(.+)\.java$}) { |m| "tests/src/#{m[1]}Test.java" } # when source files change, run the test for that file
end
